{% set data = load_setup_py_data() %}

package:
  name: module-2-library
  version: {{ data.get('version') }}

source:
  path: ../

build:
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - m2l = m2l:cli

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - click
    - jinja2

test:
  requires:
    - pytest

  imports:
    - m2l

  commands:
    - m2l --help

about:
  description: Create Python packages from single modules
  author: Brendan Collins and Carlos H Brandt
